<dl class="dl-horizontal">
    <#if reportModel.relatedResources.windupAbout.windupRuntimeVersion?has_content>
        <dt>Generated By</dt>
        <dd>${getWindupBrandName()} ${reportModel.relatedResources.windupAbout.windupRuntimeVersion}</dd>
    </#if>

    <dt>Website</dt>
    <dd><a href="https://windup.github.io/">https://windup.github.io/</a></dd>

    <dt>Documentation</dt>
    <dd><a href="https://windup.github.io/">https://windup.github.io/</a></dd>
</dl>

<dl class="dl-horizontal">
    <dt>GitHub Source</dt>
    <dd><a href="https://github.com/windup/windup">https://github.com/windup/windup</a></dd>

    <dt>GitHub Wiki</dt>
    <dd><a href="https://github.com/windup/windup/wiki">https://github.com/windup/windup/wiki</a></dd>

    <dt>Discussion Forum</dt>
    <dd><a href="https://developer.jboss.org/en/windup?view=discussions">https://developer.jboss.org/en/windup</a></dd>

    <dt>Mailing List</dt>
    <dd><a href="https://lists.jboss.org/mailman/listinfo/windup-dev">https://lists.jboss.org/mailman/listinfo/windup-dev</a></dd>

    <dt>Issues Tracking</dt>
    <dd><a href="https://issues.jboss.org/browse/WINDUP">https://issues.jboss.org/browse/WINDUP</a></dd>
</dl>