<dl class="dl-horizontal">
    <#if reportModel.relatedResources.windupAbout.windupRuntimeVersion?has_content>
        <dt>Generated By</dt>
        <dd>${getWindupBrandName()} ${reportModel.relatedResources.windupAbout.windupRuntimeVersion}</dd>
    </#if>

    <dt>Website</dt>
    <dd><a href="https://developers.redhat.com/products/mta/overview/">https://developers.redhat.com/products/mta/overview/</a>
    </dd>

    <dt>Documentation</dt>
    <dd><a href="https://access.redhat.com/documentation/en-us/migration_toolkit_for_applications/">https://access.redhat.com/documentation/en-us/migration_toolkit_for_applications/</a>
    </dd>
</dl>

<dl class="dl-horizontal">
    <#if reportModel.relatedResources.windupAbout.windupRuntimeVersion?has_content>
        <dt>Generated By</dt>
        <dd>${getWindupBrandName()} ${reportModel.relatedResources.windupAbout.windupRuntimeVersion}</dd>
    </#if>

    <dt>Website</dt>
    <dd><a href="https://developers.redhat.com/products/mta/overview/">https://developers.redhat.com/products/mta/overview/</a>
    </dd>

    <dt>Documentation</dt>
    <dd><a href="https://access.redhat.com/documentation/en-us/migration_toolkit_for_applications/">https://access.redhat.com/documentation/en-us/migration_toolkit_for_applications/</a>
    </dd>
</dl>