== Windup

Windup  is an assembly of tools that support large-scale Java application modernization and migration projects across a broad range of transformations and use cases. It accelerates application code analysis, supports effort estimation, accelerates code migration, and helps you move applications to the cloud and containers. If you want to contribute or participate in developer discussions please join the [Konveyor community](https://www.konveyor.io/community/) and ping us on [slack](https://kubernetes.slack.com/archives/CR85S82A2).


=== Installation and Usage

Windup is the upstream project that is used to build the downstream Red Hat Migration Toolkit for Applications. [The Red Hat Developers website](https://developers.redhat.com/products/mta/overview) contains a comprehensive set of [documentation](https://developers.redhat.com/products/mta/getting-started). The latest release can be downloaded from [here](https://developers.redhat.com/products/mta/download).

The cli distribution ([guide](https://access.redhat.com/documentation/en-us/migration_toolkit_for_applications/5.3/html/cli_guide/index)) contains a sample file to try Windup with. Try the following command in a console:

    bin/windup-cli --target eap7 --input samples/jee-example-app-1.0.0.ear

This will create a report next to the scanned archive:

    samples/jee-example-app-1.0.0.ear.report/index.html

=== Issue Tracker

[https://issues.redhat.com/projects/WINDUP/issues](https://issues.redhat.com/projects/WINDUP/issues)


=== Project Source Code Format

This project has an agreed upon source format style documented via an
link:https://github.com/windup/windup/blob/master/ide-config/Eclipse_Code_Format_Profile.xml[Eclipse code formatter profile].
If using an alternate IDE, plugins are available to allow use of this profile (see below).
All contributions should be formatted using this profile before submission.

* Netbeans: http://plugins.netbeans.org/plugin/50877/eclipse-code-formatter-for-java
* IntelliJ: http://plugins.jetbrains.com/plugin/?id=6546

