== Windup

Windup is an automated application migration and assessment tool.
If you want to contribute or participate in developer discussions,
join us on the `irc.freenode.net` `#windup` channel
or subscribe to the link:https://lists.jboss.org/mailman/listinfo/windup-dev[windup-dev mailing list].

== Get involved

* Windup Wiki: https://github.com/windup/windup/wiki
  ** Windup documentation is on the wiki:
    https://github.com/windup/windup/wiki/User-Guide[User Guide],
    https://github.com/windup/windup/wiki/Rules-Development-Guide[Rules Development Guide],
    https://github.com/windup/windup/wiki/Core-Development-Guide[Core Development Guide]
* Forums: https://developer.jboss.org/en/windup
* Issue Tracker: https://issues.jboss.org/browse/WINDUP
* Users Mailing List: windup-users@lists.jboss.org
* Developers Mailing List: windup-dev@lists.jboss.org
* Commits Mailing List: windup-commits@lists.jboss.org


=== Installation and Usage

You may download the link:http://windup.jboss.org/download.html[latest Windup release].
After that, follow the link:https://github.com/windup/windup/wiki/Execute[User Guide, Execute Windup].

Windup distribution contains a sample file to try Windup with. Try the following command in a console:

    bin/windup-cli --target eap7 --input samples/jee-example-app-1.0.0.ear

This will create a report next to the scanned archive:

    samples/jee-example-app-1.0.0.ear.report/index.html


=== Project Source Code Format

This project has an agreed upon source format style documented via an
link:https://github.com/windup/windup/blob/master/ide-config/Eclipse_Code_Format_Profile.xml[Eclipse code formatter profile].
If using an alternate IDE, plugins are available to allow use of this profile (see below).
All contributions should be formatted using this profile before submission.

* Netbeans: http://plugins.netbeans.org/plugin/50877/eclipse-code-formatter-for-java
* IntelliJ: http://plugins.jetbrains.com/plugin/?id=6546

