== Windup 2.0

Get involved at: http://windup.jboss.org

* Forums: https://community.jboss.org/en/windup
* Issue Tracker: https://issues.jboss.org/browse/WINDUP
* Users Mailing List: windup-users@lists.jboss.org
* Dev Mailing List: windup-dev@lists.jboss.org
* Commits Mailing List: windup-commits@lists.jboss.org


=== Looking for stable Windup 0.68 source code?

Visit https://github.com/windup/windup-legacy 

=== Project Source Code Format

This project has an agreed upon source format style documented via an Eclipse code formatter profile ( https://github.com/windup/windup/blob/master/Eclipse_Code_Format_Profile.xml ). If using an alternate IDE, plugins are available to allow use of this profile (see below.) All contributions should be formatted using this profile before submission.

* Netbeans: http://plugins.netbeans.org/plugin/50877/eclipse-code-formatter-for-java
* IntelliJ: http://plugins.jetbrains.com/plugin/?id=6546

=== Installation and Usage

To install an alpha release of Windup, simply take the following steps:

1. Configure your Maven settings to use the JBoss Nexus community repository: 
http://repository.jboss.org/nexus/content/groups/public/. 
If you are new to Maven, details on how to configure Maven can be found here: 
https://community.jboss.org/wiki/MavenGettingStarted-Users.

2. Install Forge 2 from:
https://github.com/forge/core#jboss-forge-20

3. Run the `forge` cli or Eclipse plugin with `CTRL+4`
+
[source,text]
----
localhost:Desktop user$ forge
    _____                    
   |  ___|__  _ __ __ _  ___ 
   | |_ / _ \| `__/ _` |/ _ \  \\
   |  _| (_) | | | (_| |  __/  //
   |_|  \___/|_|  \__, |\___| 
                   |___/      
JBoss Forge, version [ 2.4.2-SNAPSHOT ] - JBoss, by Red Hat, Inc. [ http://forge.jboss.org ]
----

4. Run "addon-install" with the following parameters:
+
[source,text]
----
[bin]$ addon-install --groupId org.jboss.windup.legacy.application --name legacy-windup --version 2.0.0.Alpha1
----

5. Run windup-1x via forge. Example:
+
[source,text]
----
run-windup-1-x --input input --output output --packages pkg --excludeBuiltinRules --supplementalRulesFolder /path/to/my/rules
----
+
TIP:: A supplemental rules folder should contain all rules with the naming convention (*.windup.xml).

For reference, if all goes well, your terminal should look something like this:

[source,text]
----
localhost:Desktop user$ forge
    _____                    
   |  ___|__  _ __ __ _  ___ 
   | |_ / _ \| `__/ _` |/ _ \  \\
   |  _| (_) | | | (_| |  __/  //
   |_|  \___/|_|  \__, |\___| 
                   |___/      
JBoss Forge, version [ 2.4.2-SNAPSHOT ] - JBoss, by Red Hat, Inc. [ http://forge.jboss.org ]

[Desktop]$ 
[Desktop]$ addon-install --groupId org.jboss.windup.legacy.application --name legacy-windup --version 2.0.0.Alpha1
***SUCCESS*** Addon org.jboss.windup.legacy.application:legacy-windup,2.0.0.Alpha1 was installed successfully.
[Desktop]$ 
[Desktop]$ 
[Desktop]$ run-windup-1-x 
--input  --output  --packages  --excludePackages  --fetchRemote  --sourceMode  --targetPlatform  --supplementalRulesFolder  --excludeBuiltinRules  
[Desktop]$ 
[Desktop]$ run-windup-1-x 
----

You can also get information on the command by typing `man run-windup-1-x`
