== Windup 2.0

NOTE:: The Windup 2.0 project is currently under development.
If you want to contribute or participate in developer discussions,
join us on the `irc.freenode.net` `#windup` channel 
or subscribe to the link:https://lists.jboss.org/mailman/listinfo/windup-dev[windup-dev mailing list].

== Get involved

* Windup Wiki: https://github.com/windup/windup/wiki
* Windup documentation (generated from above wiki): http://windup.github.io/windup/docs/latest/html/WindupUserGuide.html
* Forums: https://community.jboss.org/en/windup
* Issue Tracker: https://issues.jboss.org/browse/WINDUP
* Users Mailing List: windup-users@lists.jboss.org
* Developers Mailing List: windup-dev@lists.jboss.org
* Commits Mailing List: windup-commits@lists.jboss.org


=== Installation and Usage

You may download the link:https://repository.jboss.org/nexus/content/repositories/releases/org/jboss/windup/windup-distribution/[latest Windup release from JBoss.org Maven Repository].
After that, follow the link:https://github.com/windup/windup/wiki/Execute[User Guide, Execute Windup].

=== Project Source Code Format

This project has an agreed upon source format style documented via an 
link:https://github.com/windup/windup/blob/master/ide-config/Eclipse_Code_Format_Profile.xml[Eclipse code formatter profile].
If using an alternate IDE, plugins are available to allow use of this profile (see below).
All contributions should be formatted using this profile before submission.

* Netbeans: http://plugins.netbeans.org/plugin/50877/eclipse-code-formatter-for-java
* IntelliJ: http://plugins.jetbrains.com/plugin/?id=6546

