== Windup

Windup  is an assembly of tools that support large-scale Java application modernization and migration projects across a broad range of transformations and use cases. It accelerates application code analysis, supports effort estimation, accelerates code migration, and helps you move applications to the cloud and containers. If you want to contribute or participate in developer discussions please join the link:https://www.konveyor.io/community/[Konveyor community] and ping us on link:https://kubernetes.slack.com/archives/CR85S82A2[slack].


=== Installation and Usage

Download the latest Windup release from link:https://windup.github.io/downloads/[here] and refer to the link:https://windup.github.io/blog/getting-started/[getting started blog] to run your first code analysis.

=== Issue Tracker

link:https://issues.redhat.com/projects/WINDUP/issues[https://issues.redhat.com/projects/WINDUP/issues]


=== Project Source Code Format

This project has an agreed upon source format style documented via an
link:https://github.com/windup/windup/blob/master/ide-config/Eclipse_Code_Format_Profile.xml[Eclipse code formatter profile].
If using an alternate IDE, plugins are available to allow use of this profile (see below).
All contributions should be formatted using this profile before submission.

* Netbeans: http://plugins.netbeans.org/plugin/50877/eclipse-code-formatter-for-java
* IntelliJ: http://plugins.jetbrains.com/plugin/?id=6546

