package org.jboss.windup.tooling;

import org.jboss.windup.exec.WindupProgressMonitor;

import java.util.logging.LogRecord;

/**
 * Extends the standard progress monitor to also tie in with the logging system. Messages from Java Util Logging (aka JUL)
 * will be passed through this if the provided listener is an instance of {@link WindupToolingProgressMonitor}.
 *
 * @author <a href="mailto:jesse.sightler@gmail.com">Jesse Sightler</a>
 */
public interface WindupToolingProgressMonitor extends WindupProgressMonitor
{
    /**
     * Called for each {@link LogRecord} generated by Windup.
     */
    void logMessage(LogRecord logRecord);
}
