package org.jboss.windup.gui.components;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Collection;
import java.util.List;

import javax.swing.JPanel;

import org.jboss.windup.exec.configuration.WindupConfiguration;
import org.jboss.windup.gui.services.InputScanner;
import org.jboss.windup.rules.apps.java.config.ExcludePackagesOption;
import org.jboss.windup.rules.apps.java.config.ScanPackagesOption;

/**
 * Select which packages to scan.
 * 
 * @author jsightler
 */
public class SelectPackagesForm extends JPanel implements WizardStep
{
    private static final long serialVersionUID = 1L;

    private IncludeExcludePickList packagesPickList;
    private WindupConfiguration configuration;

    /**
     * Creates new form SelectPackagesForm
     */
    public SelectPackagesForm()
    {
        initComponents();
    }

    private void loadComponentData()
    {
        Path inputPath = configuration.getInputPath();
        if (inputPath != null && Files.exists(inputPath))
        {
            InputScanner scanner = new InputScanner(inputPath);
            Collection<String> packages = scanner.findPackages();
            packagesPickList.setAvailableItems(packages);
            packagesPickList.setAllListDescription("All Packages");
            packagesPickList.setIncludeListDescription("Selected Package Prefixes to Scan");
            packagesPickList.setExcludeListDescription("Selected Package Prefixes to Exclude");
        }
    }

    @Override
    public void init(WindupConfiguration cfg)
    {
        this.configuration = cfg;
        loadComponentData();
    }

    @Override
    public void stepComplete()
    {
        List<String> scanPackagesList = packagesPickList.getIncludedItems();
        List<String> excludePackagesList = packagesPickList.getExcludeItems();

        this.configuration.setOptionValue(ScanPackagesOption.NAME, scanPackagesList);
        this.configuration.setOptionValue(ExcludePackagesOption.NAME, excludePackagesList);
    }

    @Override
    public boolean validateStep()
    {
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()
    {

        packagesPickList = new org.jboss.windup.gui.components.IncludeExcludePickList();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(packagesPickList, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    );
        layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(packagesPickList, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    );
    }
}
